### PR TITLE
:ambulance: fix non-unique tokens on module installation

### LINKED ISSUE #74: open api [13.0] - openapi_token not unique
When installing the module on a database with multiple users, all users get the same openapi_token which results in a singleton error when making an API call.

I think the openapi_token should get a unqiue contraint and in addition the token should be regenerated per user when getting the default token, or a token should only be created on request?

@aschenkels-ictstudio

### PR DESCRIPTION
**Pull request by yelizariev**
closes #74

### CODE REVIEW

**Comment by yelizariev** [comment]
tested on runbot: 

* uninstall module
* install module
* RESULT: all user have different tokens

**Comment by yelizariev** [comment]
Hmm, seems that the original problem was reproducible only in non-demo installation

**Review by CasVissers-360ERP — APPROVED** [review]
Users got different tokens on module installation! Fix works for me. Thnx 👍

**Comment by yelizariev** [comment]
I approve to merge it now

**Pull request merged**
