### PR TITLE
14.0 sync add trigger fields

### PR DESCRIPTION
**Pull request by mentalko**
fix of https://github.com/itpp-labs/sync-addons/issues/325

### CODE REVIEW

**Review by yelizariev — APPROVED** [review]
Чётко

**Comment by trojikman** [comment]
via Hubstaff
User: Denis Mudarisov

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 09/02/21 - 09/02/21
Work session total: 0:08:24
Billable: Yes

Grand total: 0:08:24

**Review by trojikman — APPROVED** [review]

**Comment by trojikman** [comment]
I approve to merge it now

**Comment by trojikman** [comment]
via Hubstaff
User: Denis Mudarisov

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 09/03/21 - 09/03/21
Work session total: 0:35:21
Billable: Yes

Grand total: 0:43:45

**Comment by trojikman** [comment]
via Hubstaff
User: Denis Mudarisov

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 09/03/21 - 09/03/21
Work session total: 0:54:23
Billable: Yes

Grand total: 1:38:08

**Pull request merged**
