### PR TITLE
:arrow_up::one::three: openapi

### PR DESCRIPTION
**Pull request by yelizariev**

### CODE REVIEW

**Comment by yelizariev** [comment]
Next things to fix: 

    odoo.models:3501 create ir.actions.act_window.create() with unknown fields: view_type
    openapi/models/openapi_access.py:490: [W0622(redefined-builtin), getmembers] Redefining built-in 'object'


```

2019-10-07 14:28:10,271 5571 INFO openerp_test werkzeug: 127.0.0.1 - - [07/Oct/2019 14:28:10] "PATCH /api/v1/demo/res.partner/14/call/message_post HTTP/1.1" 501 - 38 0.016 0.027
2019-10-07 14:28:10,275 5571 INFO openerp_test odoo.addons.openapi.tests.test_api: ======================================================================
2019-10-07 14:28:10,276 5571 ERROR openerp_test odoo.addons.openapi.tests.test_api: FAIL: TestAPI.test_call_allowed_method_on_singleton_record
Traceback (most recent call last):
File "/home/travis/build/it-projects-llc/sync-addons/openapi/tests/test_api.py", line 136, in test_call_allowed_method_on_singleton_record
self.assertEqual(resp.status_code, pinguin.CODE__success)
AssertionError: 501 != 200

```


```
2019-10-07 14:28:10,826 5571 INFO openerp_test werkzeug: 127.0.0.1 - - [07/Oct/2019 14:28:10] "GET /api/v1/demo/res.partner HTTP/1.1" 401 - 3 0.001 0.004
2019-10-07 14:28:10,830 5571 INFO openerp_test odoo.addons.openapi.tests.test_api: ======================================================================
2019-10-07 14:28:10,830 5571 ERROR openerp_test odoo.addons.openapi.tests.test_api: FAIL: TestAPI.test_user_not_allowed_for_namespace
Traceback (most recent call last):
File "/home/travis/build/it-projects-llc/sync-addons/openapi/tests/test_api.py", line 123, in test_user_not_allowed_for_namespace
self.assertEqual(resp.json()['error'], pinguin.CODE__user_no_perm[1])
AssertionError: 'Authentication' != 'Permissions'
- Authentication
+ Permissions
2019-10-07 14:
```

**Review by Ramil-Mukhametzyanov — APPROVED** [review]

**Review by Ramil-Mukhametzyanov — COMMENTED** [review]
There is no module name in the PR title.

**Comment by yelizariev** [comment]
LINT error will be fixed on porting updates from 12 version

**Comment by NigmatullinAN** [comment]
I approve to merge it now

**Pull request merged**
