### PR TITLE
14.0 sync

### PR DESCRIPTION
**Pull request by yelizariev**

### CODE REVIEW

**Comment by yelizariev** [comment]
@trojikman можно проверять. Я только оду2оду проверил

**Review by trojikman — CHANGES_REQUESTED** [review]
It happens at installation
```
odoo.modules.loading: The model sync.make.module has no access rules, consider adding one. E.g. access_sync_make_module,access_sync_make_module,model_sync_make_module,base.group_user,1,0,0,0 

```

This happens while I send message to the Telegram Bot
Screenshot from 2021-02-16 12-12-24

**Review by trojikman — COMMENTED** [review]
Этого недостаточно
Screenshot from 2021-02-17 12-19-30

**Comment by yelizariev** [comment]
Проверил -- работает

image

image

**Comment by trojikman** [comment]
I can't understand where can I unarchive it?
Screenshot from 2021-02-22 23-52-53

**Comment by trojikman** [comment]
For some reason, it creates two cards when I creating one issue
Screenshot from 2021-02-23 17-52-04

**Review by trojikman — APPROVED** [review]

**Pull request merged**
